version: "3"

services:
  postgres:
    container_name: postgres_container1
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

    restart: unless-stopped

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  php:
    ports:
      - 9822:80
    image: thecodingmachine/php:8.1-v4-apache-node18
    container_name: testlaravue
    restart: unless-stopped
    volumes:
      - './:/var/www/html'
    extra_hosts: # <-- this is required
      - "host.docker.internal:host-gateway" # <-- this is required
    environment:
        TZ: UTC
        PHP_EXTENSION_PGSQL: 1
        PHP_EXTENSION_PDO_PGSQL: 1
        PHP_EXTENSION_MYSQLI: 0
        PHP_EXTENSION_GD: 1
        PHP_EXTENSION_IMAGICK: 1
        PHP_EXTENSION_EXIF: 1
        PHP_EXTENSION_ZIP: 1
        PHP_EXTENSION_GMP: 1
        PHP_EXTENSION_IMAP: 1
        PHP_INI_MAX_EXECUTION_TIME: 300
        PHP_INI_MAX_INPUT_TIME: 300
        PHP_INI_MEMORY_LIMIT: 512M
        PHP_INI_POST_MAX_SIZE: 20M
        PHP_INI_UPLOAD_MAX_FILESIZE: 20M
        APACHE_DOCUMENT_ROOT: public
        APACHE_RUN_USER: www-data
        APACHE_RUN_GROUP: www-data
        # STARTUP_COMMAND_0: "sudo chmod -R 777 /var/www/html/bootstrap/cache"
        # STARTUP_COMMAND_0: "sudo chmod -R 777 /var/www/html/bootstrap/cache"
        STARTUP_COMMAND_1: "COMPOSER_MEMORY_LIMIT=-1 composer install"
        # STARTUP_COMMAND_2: "npm install"
        # STARTUP_COMMAND_3: "php artisan storage:link"
        STARTUP_COMMAND_4: "sudo chmod 777 -R storage/"
        STARTUP_COMMAND_5: "php artisan key:generate"
        STARTUP_COMMAND_6: "npm install"
        #STARTUP_COMMAND_5: "npm install laravel-mix@latest"
        # STARTUP_COMMAND_6: "npm run dev"

volumes:
  postgres:
